### ISSUE TITLE
能否在列表添加单任务的上行速度及添加种子任务时候自定义单任务的路径？

### ISSUE THREAD

**Issue by evilkong** [mayswind/AriaNg#21]
rt。这webui真的很不错。只是我主要用来挂tp的，但现在的问题是，添加种子的时候，路径是默认的，我无法在后面自定义后面的目录，之前用的yaaw可以。另外我下载之后一般都会留作种子上传的，需要直接关注一下每个任务的上传情况。但是目前的列表中没有。
能否考虑下添加和修改。谢谢。

**Comment by mayswind** [comment]
@evilkong 
1、添加种子的时候是可以修改目录的，用的就是“新建”->“选项”里设置的。
2、于大多数人而言，同时查看每个任务的实时上传速度并不是有特别广泛的需求，首页可以实时看全局上传速度，如果看单个任务的话，可以点开任务查看。目前来看，首页没有更合适的位置放任务的上传速度了。

**Comment by evilkong** [comment]
1、我这里定义了默认路径，新建、选项那里的默认路径是readonly，无法更改；
2、上行速度那里我做了下调整，大大看看http://9hut.net/ariang 这样是否合适。

**Comment by mayswind** [comment]
@evilkong 
1、那里不是readonly，是默认有个placeholder提醒你默认值是啥...
2、欢迎fork并修改...但我希望整体界面简洁而高效...不太能接受把一大堆东西堆一起的感觉...

**Comment by liwufan** [comment]
前面的网址失效了，我照着文档乱写了一通，大大能不能考虑一下默认下载列表，点击之后切换到上传排名这种模式？https://github.com/liwufan/AriaNg/commit/861f9cc5875a5e1df1d6371884b20463655c4689

**Comment by mayswind** [comment]
@liwufan 不能，原因参看之前贴的内容。

**Comment by Nicnl** [comment]
Please, allow me to do a recap

- #21 (`Can I customize the path of a single task when adding the single task's upstream speed and adding a seed task to the list?`)
- #24 (`Forgive me for a request, can you display the upload speed, do not click to see the upload speed of each file`)
- #84 (`How do I see the upload speed of each task?`)
- #219 (`Why doesn't the task list show upload speed?`)
- #234 (`BT shows upload speed`)
- #244 (`Uploading Speed`)
- #264 (`Displaying upload speed for seeding torrents`)
- #273 (`Torrent Upload View`)
- #322 (`add showUploadSpeedInTaskList option`)
- #343 (`Display the upload speed and total uploaded in the torrent list`)

So, AriaNg users have been *continuously* asking for such a feature, but you state that _'this is not a frequently used feature'_.  
I'm afraid I don't understand.

Would it be acceptable for you if such a feature was available in the settings, but disabled by default?  

That way:
- the UI would remain clean and mobile friendly **by default**
- the people who need this feature can still enable it in the settings if they really want to

**Comment by Nicnl** [comment]
1. Can I ask you why you are using the wording _'frequently used'_ then?  
Since this feature was never made available at any point in time, both me and you have no metrics on how much it's used.  
Only how much people are requesting it.
2. I wouldn't qualify a feature as being _'meaningless'_ when 10 issues with dozens of users are requesting it because they need it.  
(Maybe saying 'meaningless to you' would be a wiser wording?)
3. I would like to understand why.  
Making it optional and disabling it by default will resolve the main concern you expressed, which was making it mobile friendly.

I feel that this is needlessly spiting on many use cases.

**Comment by mayswind** [comment]
@Nicnl 
I think it has been explained very clearly. There is no need to explain it anymore.
