### ISSUE TITLE
NO Chinece

### ISSUE THREAD

**Issue by Xianbei233** [mayswind/AriaNg#54]
choose the language to chinese and refresh ， but nothing happen

**Comment by mayswind** [comment]
I guess you open index.html from local folder, and change the language to "Simplified Chinese".

Since AriaNg loads language resources asynchronously, you may not open index.html directly on the local file system to run AriaNg. It is recommended that you deploy AriaNg in a web container or download [AriaNg Native](https://github.com/mayswind/AriaNg-Native) that does not require a browser to run.

**Comment by Xianbei233** [comment]
thanks, problem solved.
