### ISSUE TITLE
Feature request:  Automatically select and download files according to configurable rules

### ISSUE THREAD

**Issue by YanceyChiew** [mayswind/AriaNg#546]
When the option "pause-metadata=true" is passed to aria2c, after the metadata download is completed, it will automatically pause to wait for users to select the files they want to download.

Most of the time, the choice is so fixed that it can be summed up in simple rules. For example, when metadata contains only one file, download it directly is the only one choice, and whenever it appears "__ pading_file_%n", we always don't want to download it because it's just an alignment file.

According to the file extension, keyword, directory level and other information to automatically select whether to download or not will greatly simplify the user's operation——after all, some torrents contain too many files.

In addition, automatic file selection allows users not to always pay attention to when .torrent file downloads complete. If aria-ng can automatically pop up the file selection window when "pause metadata", it will be better.

**Comment by no1xsyzy** [comment]
You can exclude padding file in the download result, but you just cannot prevent downloading it, since it is padding file, it is contained in the same block as other files. The only exception is that you are using the same BT client which created this torrent, which actually can pseudo-download it since it knows the content in advance by the padding algorithm.
