### ISSUE TITLE
Disconnected Status due to CORS policy

### ISSUE THREAD

**Issue by hl2guide** [mayswind/AriaNg#632]
I have AriaNG Native working fine on my PC, but when I try out the All-in-one version of AriaNG and set the same RPC settings I run into an issue (disconnected).

AriaNG Version: 1.2.3
Browser: Edge (Chromium)

Error in Browser Console:
`Access to XMLHttpRequest at 'http://localhost:6800/jsonrpc' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Please consider improving the message or status for this situation and also offer a fix. 😊

![example](https://user-images.githubusercontent.com/17044982/146060338-6cf929c4-0826-4770-a1dd-730261ebf5ff.png)

**Comment by no1xsyzy** [comment]
It is impossible for any message improving, since this browser console error message is limited to user only. All modern browsers considers it a security issue if it can be told apart from JavaScript. The real reason why it fails can indicate if an IP:port exists in internal web, which can leak information about attack factor and your privacy.

**Comment by no1xsyzy** [comment]
BTW, the solution is to add `--rpc-allow-origin-all` to aria2 config. See the manual of aria2.

**Comment by hl2guide** [comment]
ah okay thanks for the info and the above fix @no1xsyzy ☺
