### ISSUE TITLE
Andy docker version

### ISSUE THREAD

**Issue by xinmans** [mayswind/AriaNg#720]
Please give a docker-compose.yaml file to deploy as a docker

**Comment by mayswind** [comment]
No. AriaNg will never provide any official docker image, because all of the AriaNg files only contain static files (All-In-One version is just one html file). AriaNg does not require any server-side resource or service. Providing a container which containes AriaNg static files is waste of resource.

Here is my personal suggestion:
1. If you want open AriaNg in your computer, I suggest you download the AriaNg Native or AriaNg All-In-One version.
2. If you want open AriaNg in browser of mobile device, I suggest you visit any existed url which published by other people instead of deploying a new one, like http://ariang.mayswind.net/latest .
3. If you want to deploy AriaNg to the web, I suggest you can publish AriaNg to any static content hosting service, like github page.
4. If you want to deploy AriaNg to your own server, I guess you already run a web server like nginx or apache, so just deploy the static files of AriaNg to it instead of running a new web server.

duplicated with #108

**Comment by xinmans** [comment]
i will write a Dockerfile to deploy it.

Just for management easily
